// Ported verbatim from the website's explore.js (PRACTICEABLE list, PRAC_ICS,
// step arrays) so the app's Practice Methods tab has all 18 methods, not
// just the original 8.
export const METHODS = [
  {
    name: '369 Method',
    icon: '3️⃣',
    steps: [
      'Find a quiet space with a pen and paper.',
      'Write your core affirmation 3 times — morning. Really feel it as you write.',
      'Write the same affirmation 6 times — afternoon.',
      'Write the same affirmation 9 times — evening before bed.',
      'Feel the emotion of it being real with each line. Not just writing — feeling.',
      'Complete all 18 repetitions. Mark today as done.',
    ],
  },
  {
    name: '5×55 Method',
    icon: '5️⃣',
    steps: [
      'Choose ONE single affirmation. Write it here or in your mind.',
      'Write it 55 times in one sitting. Do not stop.',
      "Feel the emotion of each line — don't let it become mechanical.",
      'Complete all 55 repetitions without breaks.',
      'Mark this as Day 1. This must be done 5 consecutive days.',
      'After day 5, completely let go and trust.',
    ],
  },
  {
    name: 'Scripting',
    icon: '📝',
    steps: [
      'Open your Scripts tab or a notebook dedicated only to scripting.',
      "Write today's date — but as a date in the future when your desire has arrived.",
      'Begin: "I am so happy and grateful now that..."',
      'Describe your life in vivid sensory detail — what you see, feel, hear, smell.',
      'Write for at least 10 minutes without stopping to think.',
      'End with genuine gratitude. Re-read before bed tonight.',
    ],
  },
  {
    name: "Ho'oponopono",
    icon: '⭕',
    steps: [
      'Sit quietly. Bring your desire — or a current block — to mind.',
      'Notice any resistance, fear or anxiety that arises.',
      'Say slowly, with genuine feeling: "I\'m sorry."',
      'Then say: "Please forgive me."',
      'Then say: "Thank you."',
      'Then say: "I love you."',
      'Repeat the four phrases for 5-10 minutes. Let the emotion come if it comes.',
    ],
  },
  {
    name: 'Pillow Method',
    icon: '🌙',
    steps: [
      'Write your desire or affirmation clearly on a piece of paper.',
      'Hold the paper before bed. Read it aloud once with full belief.',
      'Feel the joy of it being real right now.',
      'Place the paper under your pillow.',
      'As you fall asleep, replay your desired reality like a movie.',
      'Do this every night until it manifests.',
    ],
  },
  {
    name: 'Mirror Work',
    icon: '🪞',
    steps: [
      'Stand in front of a mirror. Look directly into your own eyes.',
      'Begin with: "I love you, [your name]." Say it until you believe it.',
      'Speak your main affirmation aloud with full eye contact.',
      'Notice any resistance or discomfort — breathe through it gently.',
      'End with: "I love you and I believe in you."',
      'Do this every morning for 30 days.',
    ],
  },
  {
    name: 'Two Cup Method',
    icon: '🥤',
    steps: [
      'Fill two cups with water.',
      'Label one cup with your current situation.',
      'Label the other with your desired reality.',
      'Hold the first cup, feel your current reality fully.',
      'Slowly pour the water into the second cup while visualising the shift.',
      'Drink the water from the desire cup with full belief.',
      'Discard the labels. Let go completely.',
    ],
  },
  {
    name: 'Water Manifestation',
    icon: '🌊',
    steps: [
      'Fill a glass with clean water.',
      'Hold the glass with both hands.',
      'Close your eyes and speak your intention into the water three times.',
      'Feel the emotion of your desire as already real.',
      'Drink the water slowly and mindfully.',
      'Trust that the intention has been received.',
    ],
  },
  {
    name: 'Visualisation',
    icon: '🔮',
    steps: [
      'Find a quiet space and close your eyes.',
      'Take 10 slow deep breaths until your body relaxes completely.',
      'Build your desired reality in your mind — start with the environment.',
      'Add people, sounds, textures, scents. Make it multi-sensory.',
      'Feel the emotion of it being real right now — gratitude, joy, peace.',
      'Stay in the vision for at least 10 minutes without breaking it.',
      'Open your eyes slowly. Carry that feeling through your day.',
    ],
  },
  {
    name: 'Neville Revision',
    icon: '🎬',
    steps: [
      'Think of an event from today or recently that did not go as you wanted.',
      'Close your eyes and fully relive it — but rewrite it as you wanted it to go.',
      'See the new version play out vividly. Feel the positive outcome.',
      'Repeat the revised scene at least 3 times until it feels natural.',
      'Fall asleep (or end your session) holding the feeling of the revised outcome.',
      'Trust that the new version rewires your subconscious expectation.',
    ],
  },
  {
    name: 'Whisper Method',
    icon: '🤫',
    steps: [
      'Choose a specific person or situation you want to influence.',
      'Sit quietly and visualise that person or situation in front of you.',
      'In your mind, whisper your desired message to them 3 times.',
      'Feel it as real — see them receiving and responding positively.',
      'Release with genuine gratitude. Do not obsess over the outcome.',
      'Repeat once a day for 7 days.',
    ],
  },
  {
    name: 'Focus Wheel',
    icon: '☸️',
    steps: [
      'Draw a circle. Write your desire in the centre.',
      'Around the outside, write 12 statements that feel true right now and move toward the desire.',
      'Start with statements that feel slightly believable, not giant leaps.',
      'Read each statement aloud. Notice how your energy shifts with each one.',
      'End with the closest statement to your desire you truly believe.',
      'Use this as your affirmation for the next 3 days.',
    ],
  },
  {
    name: 'Rampage of Appreciation',
    icon: '🎉',
    steps: [
      'Set a timer for 5 minutes.',
      'Begin speaking or writing everything you appreciate — no filter.',
      'Start small: your breath, sunlight, your phone, your hands.',
      'Build momentum — let appreciation expand to bigger things.',
      "Notice when you feel a shift in your body — that's the frequency rising.",
      'End with 3 things you appreciate about your desire as if it is real.',
    ],
  },
  {
    name: '17-Second Method',
    icon: '⏱️',
    steps: [
      'Choose one pure positive thought about your desire.',
      'Hold that single thought with full focus for 17 seconds. Do not let it waver.',
      'Notice the feeling — it should feel like a gentle energetic buzz.',
      'If you held it: chain the next related positive thought for another 17 seconds.',
      'Repeat for 68 seconds total (4 segments) for maximum momentum.',
      'Do not force — stop if resistance arises. Come back later.',
    ],
  },
  {
    name: 'Assumption Method',
    icon: '🎭',
    steps: [
      'Identify one core assumption you need to hold for your desire to be real.',
      'Example: "I assume I am already financially free."',
      'Write the assumption in first person, present tense.',
      'For the next 48 hours, behave as if this assumption is simply true.',
      'Notice every thought that contradicts it. Replace it with the assumption.',
      'Let the assumption become your new default state of being.',
    ],
  },
  {
    name: 'Gratitude Practice',
    icon: '🙏',
    steps: [
      'Open your journal or the Gratitude section.',
      'Write 10 things you are genuinely grateful for — include your desire as if received.',
      'For each item, feel the gratitude in your body before moving to the next.',
      'End with: "Thank you for the miracles I have not yet seen."',
      'Do this morning and evening for 21 days.',
    ],
  },
  {
    name: 'EFT Tapping',
    icon: '👐',
    steps: [
      'Identify a specific block or negative feeling about your desire.',
      'Rate the intensity 0-10.',
      'Tap the karate chop point while saying: "Even though I feel [block], I deeply love and accept myself." 3×',
      'Tap through 8 points (eyebrow, side eye, under eye, under nose, chin, collarbone, under arm, top of head).',
      'At each point, speak your block aloud. Then speak your desired feeling.',
      'Re-rate the intensity. Repeat until below 3.',
      'End with a positive round — tap through all 8 points stating your desire as real.',
    ],
  },
  {
    name: 'Letting Go',
    icon: '🕊️',
    steps: [
      'Identify a desire you have been gripping tightly.',
      'Write: "I want this. I am ready to release my attachment to how or when it arrives."',
      'Take a deep breath in. Breathe out and physically open your hands.',
      'Say aloud: "I surrender this to the universe. I trust the timing."',
      'Write 3 ways you can enjoy your life fully right now, without the desire.',
      'Notice the relief. That feeling of release is the frequency of receiving.',
    ],
  },
];

// ── Synchronicity Log ───────────────────────────────────────────────────
export const SYNC_TAGS = ['🔢 Numbers', '🌸 Coincidence', '🎁 Gift', '💭 Thought', '🌟 Other'];

// ── Journal Prompt ───────────────────────────────────────────────────────
export const JOURNAL_PROMPTS_GENERAL = [
  'What would your life look like if you already had everything you desired?',
  'What is one belief you are ready to release today?',
  'Describe a moment when you felt truly aligned. What made it possible?',
  'What would you do differently if you knew you could not fail?',
  'Write a thank-you letter to the universe for something not yet received.',
  'What does abundance feel like in your body right now?',
  'Who would you be without your biggest fear?',
  'What is the universe trying to tell you this week?',
  'Describe your ideal day in complete detail — as if it is already real.',
  'What are you most grateful for that you once thought was impossible?',
  'What old story are you ready to stop telling about yourself?',
  'Write about a time you trusted and it worked out beautifully.',
  'What does your dream life feel like in your body?',
  'What is one small action your future self would take today?',
  'Write three things that are already going right in your life.',
  'What would you do if money was not a factor at all?',
  'Describe the version of you that has everything you desire.',
  'What are you ready to receive?',
  "How would your future self handle today's challenges?",
  'Write about a desire as if it has already arrived.',
  'What does love feel like in your ideal relationship?',
  'What are you willing to let go of to make space for what you want?',
  'Describe the feeling of waking up in your dream life.',
  'What is the universe conspiring in your favour right now?',
  'What have you been putting off that your soul is calling you to do?',
  'Write a message from your higher self to your present self.',
  'What would it feel like to be completely financially free?',
  'What do you love most about yourself?',
  'Describe the moment your biggest desire finally arrived.',
  'What does success mean to you — not to anyone else?',
  'Write about who you are becoming.',
  'What does your body feel like when you are completely well and vibrant?',
  'What is one thing you want to stop apologising for?',
  'Describe the home you are calling in. Every detail.',
  'What qualities does your ideal partner embody?',
  'What do you want your life to stand for?',
  'What brings you the most joy and how can you add more of it today?',
  'Write about a version of you who is completely at peace.',
  'What are three things you are manifesting right now?',
  'What does your soul actually want — beneath all the noise?',
  'Describe a day in the life of your most abundant self.',
  'What would you do with complete freedom?',
  'Write about a dream that still feels too big. Make it bigger.',
  'What does it mean to truly trust the process?',
  'What are you no longer available for?',
  'How has the universe already been supporting you?',
  'Write about what you want to feel — not just what you want to have.',
  'What does your highest self look like right now?',
  'Describe one moment of pure magic in your life.',
  'What are you deeply proud of that you rarely acknowledge?',
  'Write about what happens the day your biggest dream arrives.',
  'What does living in alignment mean to you?',
  'Write 10 things your future self loves about life.',
  'What would you tell your past self about where you are now?',
  'What is love teaching you right now?',
  'Describe what it feels like to have your dream career.',
  'What are three things your body is doing well today?',
  'Write about how it feels to be deeply known and truly loved.',
  'What is one miracle you are calling in?',
  'What does it feel like to be exactly where you are meant to be?',
];

export const JOURNAL_CATEGORIES = {
  general: { ic: '✨', label: 'General', prompts: JOURNAL_PROMPTS_GENERAL.filter((_, i) => i % 6 === 0) },
  money: {
    ic: '💰', label: 'Money',
    prompts: [
      'What is my current relationship with money?',
      'What would financial freedom feel like in my body?',
      'What limiting belief about money am I ready to release?',
      'Write a day in the life of your most financially abundant self.',
      'What does money allow you to be, do and have?',
      'I am becoming someone who...when it comes to money.',
    ],
  },
  love: {
    ic: '💕', label: 'Love',
    prompts: [
      'What does my ideal relationship feel like moment to moment?',
      'What do I need to heal to fully receive love?',
      'Describe your soulmate — their energy, not their looks.',
      'How do I want to feel in my relationship every day?',
      'Write a letter from your future self in your dream relationship.',
      'I am becoming someone who...in relationships.',
    ],
  },
  health: {
    ic: '🌿', label: 'Health',
    prompts: [
      'What does it feel like to be in my healthiest, most vibrant body?',
      'What does my body need from me today?',
      'Write a letter of gratitude to your body.',
      'What habits does my healthiest self have?',
      'Describe a day in the life of your most energetic, radiant self.',
      'I am becoming someone who...when it comes to my health.',
    ],
  },
  mindset: {
    ic: '🧠', label: 'Mindset',
    prompts: [
      'What old story am I ready to stop telling about myself?',
      'What would I do if I knew I could not fail?',
      'Who am I becoming through this process?',
      'What belief, if I released it today, would change everything?',
      'Write about a version of you who trusts themselves completely.',
      'I am becoming someone who...',
    ],
  },
  gratitude: {
    ic: '🙏', label: 'Gratitude',
    prompts: [
      'Write 10 things I am deeply grateful for right now.',
      'What has the universe provided that I once doubted it could?',
      'What simple, ordinary things am I taking for granted?',
      'Write a thank-you letter to the universe.',
      'What about today can I appreciate?',
      'What miracle — big or small — happened this week?',
    ],
  },
};

// ── Abundance Cheque ─────────────────────────────────────────────────────
export const CHEQUE_STYLES = {
  blush: { label: '🌸 Blush', headerColors: ['#e8c0d0', '#d4a8c0'], bg: ['#fdf5f8', '#f5e8f0'], ink: '#4a2038', bankName: 'BANK OF INFINITE LOVE', bankSub: 'Heart Currency · Always Receiving', serial: 'LV', paid: 'RECEIVED WITH LOVE ✨', sign: 'The Universe' },
  lavender: { label: '💜 Lavender', headerColors: ['#c8b0e8', '#b098d8'], bg: ['#f8f4ff', '#e8e0fa'], ink: '#3a1a60', bankName: 'UNIVERSAL ABUNDANCE BANK', bankSub: 'Prosperity Division · Est. Always', serial: 'UV', paid: 'PAID IN FULL ✨', sign: 'The Universe' },
  gold: { label: '✨ Gold', headerColors: ['#e8c870', '#d4a840'], bg: ['#fefcf0', '#faf2d0'], ink: '#4a3800', bankName: 'GOLDEN ABUNDANCE BANK', bankSub: 'Wealth Division · Est. Always', serial: 'GA', paid: 'MANIFESTED ✨', sign: 'The Universe' },
  sage: { label: '🌿 Sage', headerColors: ['#a8c8b0', '#88b098'], bg: ['#f4faf6', '#e4f2e8'], ink: '#1a4030', bankName: 'EARTH ABUNDANCE BANK', bankSub: 'Prosperity · Growth · Gratitude', serial: 'EA', paid: 'RECEIVED & GRATEFUL ✨', sign: 'Mother Earth' },
  cream: { label: '🤍 Cream', headerColors: ['#d8c8b8', '#c8b8a8'], bg: ['#fdfcf8', '#f5f0e8'], ink: '#3a3028', bankName: 'BANK OF THE UNIVERSE', bankSub: 'Abundance Division · Est. Always', serial: 'BU', paid: 'PAID IN FULL ✨', sign: 'The Universe' },
};
